[package]
name = "yasak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0"
uuid = { version = "0.8", features = ["v4"] }
base64 = "0.13.0"
